apiVersion: redhatcop.redhat.io/v1alpha1
kind: ResourceLocker
metadata:
  name: ingress-controller-patch
  namespace: resource-locker-config
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
spec:
  serviceAccountRef:
    name: resource-locker-ingress-sa
  patches:
  - targetObjectRef:
      apiVersion: operator.openshift.io/v1
      kind: IngressController
      name: default
      namespace: openshift-ingress-operator
    patchTemplate: |
      spec:
        replicas: 3
        defaultCertificate:
          name: ingress-wildcard
        nodePlacement:
          nodeSelector:
            matchLabels:
              node-role.kubernetes.io/worker: ""
    patchType: application/merge-patch+json
    id: ingress-controller-patch