apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ldap-secret
  namespace: openshift-config
spec:
  encryptedData:
    bindPassword: AgALBYQFpgZ1cSTlBPXqf9RMK5JpWyhVaWFkorSaIkVjfqBSdFB9f+yXReXBZX+Pi5jwl6lHDCC9fpG/cNkE6hD5TvVRPnCtWELBJNBuvPolzAZhev84pLDaeEHQiIopRpFpFYAOIR8WeYumAe1ON/I29AgXzTgG9rKhbFgr6nIZbCLlvSa0OVt0Z4vQG0ixhB9YNJ8RTQcKsaacztTbHPCauY8Q3+X7QVhmmoIW2z1ZsxyuNGu2dvGBjyIfRBShHdxTl5ZNQh0XuSg3dPePb/nreHH21/T9I8tfP3MZBu6MFVE/VquNuDZCNdudgs+lqZA7PDyrxHPTryH+Z1eFsvAVUH26WmthkPrvfbrNCcRE6lojVgV40+77Vx5cIyFy0cAWqFkpGleOE7hjyvQWpvg4/9w8vyErYq55oaPH6hIRRaY0MkPfOFACGKQHufg9xZkb+fSxzySnUBxJol8NxNutC5hvXHAwxBLYAq/NhDpq5yAWwjMtzw6zEdoFAYlvKbvhfHOOKWN2qfUhoWyVpeyN11D5V3GvsGVjA49TBIpYzai8O2XOixR8/G1Kjz1i3fcxNIHKmQ4fhtgVA0a2TQ0pIM3gI4Kn48Q6V/kGemZ4t1XCGnUNYl48kb2fRG2pHL/+7jkCwa0O01ujggOHQRzteOxcuhdjGf4DoV1By7XHOUCT3g5XG7xa4wJucrIrPgIGzCdy+RmtAA/DdW5JqHK0aezNJQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ldap-secret
      namespace: openshift-config

