apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: htpasswd
  namespace: openshift-config
spec:
  encryptedData:
    htpasswd: AgAw9HKVYUiYx0z/nvFHbSlrwfj1xDzhcynowMPkfJ/UR3KZAGSC1TkfzMMbxUI9BFUz44ANlqEw0nDL4Z0yrEJyDPfY6Nq6AURR3KfzyiSkPGIfwavu2ToLQ3Pk+Wyqbhb8wHjkB2U4IEywy/Vt8ENN9ZYiQYdB/xZKw7uBVhmhZjDr024Jxt72mcVP+eBt5VkPUC3b8roKyReZoH8wyB1Fs00lQIszpnUiqEsmKp5w0A25huzqBsJnmqXuc7xbj+H43RuovbNNLIa42YeJ7+W2IJQMjYVJQ36FmI6nfl+iExxH4p9EMw0+i3WsoiDVubMzKDLDneiLj9ltgBj6YN5SfO5UZFoOfmLcaZclzzSYHhbEzX1soGtpu7kwhuBIwZUCh1pckEzSLsgSLRuc+DYrTQiIlTg8NmZBxLb00nYJ/9s4x3eN2FNrX+EL1l/FED4NzXJAVEh+S79/iSY8cUQSwppwIK98rx8xkgRs2UXldh1HIWMIF7XKvGq/nWCFLia4nnlgx3Kpkhxee5pc5v+igKY7R5BDC66xh94xoVsD3K+UpIUEfl5N/uYB58Ky6wuK3qKdIkazj8LY4WnZkP1fAJ1USFjck5tIGfMXQgD5xQV8s3Ax942iQQEkr1zM5hVBzYY30uMvD4dTM4rzlvB5HhqlI1Aoute+MXrhpZNRxTWtaCj1H194nR/g4cfj9Nyl9bSOSBohRonUi3DUB/NW7fR1l2itObLyKPUAe29t/FrLILaocBL6/0vMCKQnOsAKFSAYSykDkt0myZSvvXr7vzWkonY+
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: htpasswd
      namespace: openshift-config

