apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-controller
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    gitops.ownedBy: cluster-config
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: clusters/redcloud/ingress-controller/base
    repoURL: https://github.com/ocpdude/ocp-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true