apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocs
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    gitops.ownedBy: cluster-config
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: openshift-cluster/redcloud/service-operators/ocs/base
    repoURL: https://github.com/ocpdude/ocp-argocd.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true