apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proxy-service
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "5"
  labels:
    gitops.ownedBy: cluster-config
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: openshift-cluster/redcloud/proxy-service/base
    repoURL: https://github.com/ocpdude/ocp-argocd.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true