apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - subscription.yaml
  - group-sync-secret-sealed.yaml
  - ldap-group-sync.yaml
  - redcloud-idm-ca-secret-sealed.yaml