apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - subscription.yaml
  - group-sync-secret-sealed.yaml
  - ldap-group-sync.yaml

secretGenerator:
  - name: redcloud-idm-ca
    namespace: ldap-group-sync
    files:
    - ca.crt=./idm.crt