apiVersion: v1
kind: Namespace
metadata:
  name: group-sync-operator
  labels:
    openshift.io/cluster-monitoring: "true"
spec: {}

---
apiVersion: v1
kind: Namespace
metadata:
  name: ldap-group-sync
spec: {}