# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: registry-shared-storage
#   namespace: openshift-image-registry
#   # annotations:
#   #   argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
#   #   argocd.argoproj.io/sync-wave: "4"
# spec:
#   accessModes:
#   - ReadWriteMany
#   resources:
#     requests:
#       storage: 100Gi
#   # storageClassName: ocs-storagecluster-cephfs # If using OpenShift Container Storage
#     storageClassName: thin
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-registry-pv
  namespace: openshift-image-registry
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  nfs:
    path: /registry
    server: 172.16.1.5
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "image-registry-storage"
  namespace: openshift-image-registry
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
  volumeMode: Filesystem