apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resource-locker-operator/base
  - serviceaccount-node.yaml
  - serviceaccount-registry.yaml
  - clusterrole-node.yaml
  - clusterrole-registry.yaml
  - clusterrolebinding-node.yaml
  - clusterrolebinding-registry.yaml
  - clusterrole-apiserver.yaml
  - clusterrolebinding-apiserver.yaml
  - serviceaccount-apiserver.yaml
  - clusterrole-ingress.yaml
  - clusterrolebinding-ingress.yaml
  - serviceaccount-ingress.yaml
  - clusterrole-proxy.yaml
  - clusterrolebinding-proxy.yaml
  - serviceaccount-proxy.yaml
  - clusterrole-oauth.yaml
  - clusterrolebinding-oauth.yaml
  - serviceaccount-oauth.yaml