apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/resource-locker-operator.resource-locker-operator: ''
  name: resource-locker-operator
  namespace: resource-locker-operator
spec:
  channel: alpha
  name: resource-locker-operator
  source: community-operators
  sourceNamespace: openshift-marketplace


